ExamSystem.WebMVC/Areas/Teacher/Controllers/ExamController.cs
using ExamSystem.Business.Abstract;
using ExamSystem.Business.Exceptions;
using ExamSystem.Entities.Concrete;
using ExamSystem.WebMVC.Areas.Teacher.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System;
using System.Security.Claims;

namespace ExamSystem.WebMVC.Areas.Teacher.Controllers
{
    [Authorize(Roles = "Teacher")]
    [Area("Teacher")]
    public class ExamController : Controller
    {
        private IUserService _userService;
        private IExamService _examService;

        public ExamController(
            IUserService userService,
            IExamService examService
            )
        {
            _userService = userService;
            _examService = examService;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(ExamCreateModel model)
        {
            if (!ModelState.IsValid)
            {
                WebUtils.AddErrorsFromModel(ModelState);
                return View(model);
            }

            var teacherUserId = WebUtils.GetUserIdFromClaims(User);

            var exam = new Exam()
            {
                LessonName = model.LessonName,
                AnswerCount = model.AnswerCount,
                StartTime = model.StartTime,
                FinishTime = model.FinishTime,
                TeacherId = teacherUserId,
            };

            _examService.Create(exam);

            TempData["SuccessMessage"] = $"\"{exam.LessonName}\" sınavı başarılı bir şekilde oluşturuldu.";
            return RedirectToAction("Detail", new { id = exam.ExamId });
        }

        [HttpGet]
        public IActionResult Detail(int id = 1)
        {
            var teacherUserId = WebUtils.GetUserIdFromClaims(User);
            Exam exam = null;
            try
            {
                exam = _examService.GetWithAllDetailsForTeacher(id, teacherUserId);
                ViewData["Title"] = $"{exam.LessonName} - Detay";
            }
            catch (UnauthorizedException exception)
            {
                // To do exception handling
                return RedirectToAction("Index");
            }

            var model = new ExamDetailModel() { Exam = exam };
            return View(model);
        }

        [HttpPost]
        public IActionResult Delete([FromForm] int examId)
        {
            int teacherUserId = WebUtils.GetUserIdFromClaims(User);

            try
            {
                _examService.Delete(examId, teacherUserId);
            }
            catch (UnauthorizedException exception)
            {
                // To do exception handling
            }

            return RedirectToAction("Index");
        }
    }
}

ExamSystem.WebMVC/Areas/Teacher/Views/Exam/Create.cshtml
@model ExamCreateModel

<h2 class="text-primary text-center mt-8">Sınav ekle</h2>
<div class="row">
    <div class="col-10 col-sm-8 col-md-6 col-lg-4 card mx-auto mt-2">
        @if(ViewBag.ErrorMessages != null)
        {
            <div class="alert alert-danger mb-2">
                <ul>
                    @foreach(var message in ViewBag.ErrorMessages)
                    {
                        <li>@message</li>
                    }
                </ul>
            </div>
        }
        <div asp-validation-summary="ModelOnly" class="alert alert-danger mb-2"></div>
        <form asp-controller="Exam" asp-action="Create" method="post">
            <div class="form__group">
                <label class="form__label" asp-for="LessonName"></label>
                <input class="form__input" asp-for="LessonName" />
            </div>
            <div class="form__group">
                <label class="form__label" asp-for="AnswerCount"></label>
                <input class="form__input" asp-for="AnswerCount" />
            </div>
            <div class="form__group">
                <label class="form__label" asp-for="StartTime"></label>
                <input class="form__input" asp-for="StartTime" />
            </div>
            <div class="form__group">
                <label class="form__label" asp-for="FinishTime"></label>
                <input class="form__input" asp-for="FinishTime" />
            </div>
            <button class="btn btn-primary btn-block mt-2">Kaydını Tamamla</button>
        </form>
    </div>
</div>

ExamSystem.WebMVC/Areas/Teacher/Views/Exam/CreateQuestion.cshtml
@model ExamCreateQuestionModel

<h2 class="text-disabled-t mt-8"><i class="text-primary fa-solid fa-square-plus"></i> Soru Ekle - @Model.LessonName</h2>
<div class="row">
    <div class="col-12 col-md-6 col-lg-4 mx-auto mt-2">
        @if (ViewBag.ErrorMessages != null)
        {
            <div class="alert alert-danger mb-2">
                <ul>
                    @foreach (var message in ViewBag.ErrorMessages)
                    {
                        <li>@message</li>
                    }
                </ul>
            </div>
        }
        <div asp-validation-summary="ModelOnly" class="alert alert-danger mb-2"></div>
    </div>
</div>

<form class="form" asp-controller="Exam" asp-action="CreateQuestion" method="post">

    <div class="row row-align-stretch">
        <div class="col-12 col-md-6">
            <div class="card" style="height: 100%;">
                <div class="form__group">
                    <label asp-for="ExamId" class="form__label"></label>
                    <input class="form__input" readonly asp-for="ExamId" />
                </div>
                <div class="form__group">
                    <label asp-for="Text" class="form__label"></label>
                    <textarea asp-for="Text" rows="5" class="form__input" style="resize:none"></textarea>
                </div>
                <div class="form__group">
                    <label asp-for="Info" class="form__label"></label>
                    <textarea asp-for="Info" rows="5" class="form__input" style="resize:none"></textarea>
                </div>
            </div>
        </div>
        <div class="col-12 col-md-6">
            <div class="card">
                @for (int i = 0; i < Model.Answers.Length; i++)
                {
                    <div class="form__group">
                        <label class="form__label">@(i+1). Cevap</label>
                        <input class="form__input" required asp-for="@Model.Answers[i]" />
                    </div>
                }
                <div class="form__group">
                    <label class="form__label" asp-for="CorrectAnswerIndex"></label>
                    <input class="form__input" asp-for="CorrectAnswerIndex" value="1" min="1" max="@Model.Answers.Length" />
                </div>
                <button type="submit" class="btn btn-primary btn-block-fit mt-3 ml-auto">Soru Ekle</button>
            </div>
        </div>
    </div>
</form>

ExamSystem.WebMVC/Areas/Teacher/Views/Exam/Detail.cshtml
@model ExamDetailModel

@{
    var exam = Model.Exam;
    var teacher = Model.Exam.Teacher;
}

<h2 class="text-center text-disabled-t mt-5"><i class="fa-solid fa-circle-info text-primary"></i> Sınav Bilgileri</h2>
<div class="card col-12 col-md-10 col-xl-8 mx-auto mt-2">
    <div class="row row-align-flex-start">
        <div class="col-6">
            <div class="row">
                <div class="col-6">
                    <span class="text-bold text-primary">Ders Adı : </span>
                </div>
                <div class="col-6">
                    <span>@exam.LessonName</span>
                </div>
            </div>
            <div class="row">
                <div class="col-6">
                    <span class="text-bold text-primary">Başlama tarihi : </span>
                </div>
                <div class="col-6">
                    <span>@exam.StartTime</span>
                </div>
            </div>
            <div class="row">
                <div class="col-6">
                    <span class="text-bold text-primary">Bitiş tarihi : </span>
                </div>
                <div class="col-6">
                    <span>@exam.FinishTime</span>
                </div>
            </div>
            <div class="row">
                <div class="col-6">
                    <span class="text-bold text-primary">Sınav Süresi : </span>
                </div>
                <div class="col-6">
                    <span>@(exam.FinishTime.Subtract(exam.StartTime).TotalMinutes) dakika</span>
                </div>
            </div>
            <div class="row">
                <div class="col-6">
                    <span class="text-bold text-primary">Seçenek sayısı : </span>
                </div>
                <div class="col-6">
                    <span>@exam.AnswerCount</span>
                </div>
            </div>
        </div>
        <div class="col-3 ml-auto">
            <a href="#" class="btn btn-primary btn-sm btn-block"><i class="fa-solid fa-plus"></i> Soru Ekle</a>
            <a href="#" class="btn btn-warning btn-sm btn-block mt-1"><i class="fa-solid fa-plus"></i> Öğrenci Ekle</a>
            <form asp-controller="Exam" asp-action="Delete" method="post">
                <input name="examId" value="@exam.ExamId" type="hidden" />
                <button class="btn btn-danger btn-sm btn-block mt-1" type="submit"><i class="fa-solid fa-eraser"></i> Sınavı Si</button>
            </form>
        </div>
    </div>
</div>
<h2 class="text-center text-disabled-t mt-2"><i class="fa-solid fa-graduation-cap text-primary"></i> Katılan Öğrenciler</h2>
<div class="card col-12 col-md-10 col-xl-8 mx-auto mt-2">
    <div class="table-container">
        <table class="table table-striped table-no-border">
            <thead class="text-left">
                <tr>
                    <th>#</th>
                    <th>Kullanıcı adı</th>
                    <th>Ad Soyad</th>
                    <th class="text-center">-</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>1234</td>
                    <td>emreozgenc</td>
                    <td>Emre Özgenç</td>
                    <td class="text-center"><a class="btn btn-sm btn-danger" href=""><i class="fa-solid fa-eraser"></i> Kaldır</a></td>
                </tr>
                <tr>
                    <td>4321</td>
                    <td>eminozgenc</td>
                    <td>Emin Özgenç</td>
                    <td class="text-center"><a class="btn btn-sm btn-danger" href=""><i class="fa-solid fa-eraser"></i> Kaldır</a></td>
                </tr>
                <tr>
                    <td>7894</td>
                    <td>johndoe</td>
                    <td>John Doe</td>
                    <td class="text-center"><a class="btn btn-sm btn-danger" href=""><i class="fa-solid fa-eraser"></i> Kaldır</a></td>
                </tr>
                <tr>
                    <td>4567</td>
                    <td>janedoe</td>
                    <td>Jane Doe</td>
                    <td class="text-center"><a class="btn btn-sm btn-danger" href=""><i class="fa-solid fa-eraser"></i> Kaldır</a></td>
                </tr>
            </tbody>
        </table>
    </div>
</div>