ExamSystem.WebMVC/Controllers/SettingsController.cs
using ExamSystem.Business.Abstract;
using ExamSystem.Business.Exceptions;
using ExamSystem.Business.Utilities;
using ExamSystem.WebMVC.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using System;
using System.Security.Claims;

namespace ExamSystem.WebMVC.Controllers
{
    [Authorize]
    public class SettingsController : Controller
    {
        private IUserService _userService;
        public SettingsController(IUserService userService)
        {
            _userService = userService;
        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Password()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Password(PasswordModel model)
        {
            if (!ModelState.IsValid)
            {
                WebUtils.AddErrorsFromModel(ModelState);
                return View(model);
            }

            if (model.Password != model.PasswordCopy)
            {
                ModelState.AddModelError(string.Empty, Messages.PasswordsAreNotTheSame);
                return View(model);
            }

            var userId = Convert.ToInt32(User.FindFirst(ClaimTypes.NameIdentifier).Value);
            var user = _userService.Get(userId);
            user.Password = model.Password;

            try
            {
                _userService.UpdatePassword(user);
            }
            catch (ValidationException exception)
            {
                ViewBag.ErrorMessages = exception.Errors;
                return View(model);
            }
            catch (PasswordException exception)
            {
                ViewBag.ErrorMessages = exception.Errors;
                return View(model);
            }

            TempData["SuccessMessage"] = "Şifreniz başarılı bir şekilde değiştirildi.";
            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        public IActionResult Information()
        {
            var userId = Convert.ToInt32(User.FindFirst(ClaimTypes.NameIdentifier).Value);
            var user = _userService.Get(userId);

            var model = new InformationModel()
            {
                UserName = user.UserName,
                FirstName = user.FirstName,
                LastName = user.LastName,
                EMail = user.Email,
                Phone = user.Phone,
            };

            return View(model);
        }

        [HttpPost]
        public IActionResult Information(InformationModel model)
        {

            if (!ModelState.IsValid)
            {
                WebUtils.AddErrorsFromModel(ModelState);
                return View(model);
            }

            var userId = Convert.ToInt32(User.FindFirst(ClaimTypes.NameIdentifier).Value);
            var user = _userService.Get(userId);

            user.FirstName = model.FirstName;
            user.LastName = model.LastName;
            user.Phone = model.Phone;
            user.Email = model.EMail;

            try
            {
                _userService.Update(user);
            }
            catch (ValidationException exception)
            {
                ViewBag.ErrorMessages = exception.Errors;
                return View(model);
            }

            TempData["SuccessMessage"] = "Bilgileriniz başarılı bir şekilde güncellendi.";
            return RedirectToAction("Index", "Home");
        }
    }
}

ExamSystem.WebMVC/Views/Settings/Information.cshtml
@model InformationModel
@{
    Layout = "_SecondaryLayout";
}

<h2 class="text-center text-primary mt-8">Bilgilerini Güncelle</h2>
<div class="row">
    <div class="col-10 col-sm-8 col-md-6 col-lg-4 card mx-auto mt-2">
        @if (ViewBag.ErrorMessages != null)
        {
            <div class="alert alert-danger mb-2">
                <ul>
                    @foreach (var message in ViewBag.ErrorMessages)
                    {
                        <li>@message</li>
                    }
                </ul>
            </div>
        }
        <div asp-validation-summary="ModelOnly" class="alert alert-danger mb-2"></div>
        <form asp-controller="Settings" asp-action="Information" method="post">
            <div class="form__group">
                <label class="form__label" asp-for="UserName"></label>
                <input readonly class="form__input" asp-for="UserName" />
            </div>
            <div class="row">
                <div class="col-6">
                    <label class="form__label" asp-for="FirstName"></label>
                    <input class="form__input" asp-for="FirstName" />
                </div>
                <div class="col-6">
                    <label class="form__label" asp-for="LastName"></label>
                    <input class="form__input" asp-for="LastName" />
                </div>
            </div>
            <div class="row">
                <div class="col-6">
                    <label class="form__label" asp-for="EMail"></label>
                    <input class="form__input" asp-for="EMail" />
                </div>
                <div class="col-6">
                    <label class="form__label" asp-for="Phone"></label>
                    <input class="form__input" asp-for="Phone" />
                </div>
            </div>
            <button class="btn btn-primary btn-block mt-2">Bilgilerini Güncelle</button>
        </form>
    </div>
</div>

ExamSystem.WebMVC/Views/Settings/Password.cshtml
@model PasswordModel
@{
    Layout = "_SecondaryLayout";
}

<h2 class="text-center text-primary mt-8">Şifre Değiştir</h2>
<div class="row">
    <div class="col-10 col-sm-8 col-md-6 col-lg-4 card mx-auto mt-2">
        @if (ViewBag.ErrorMessages != null)
        {
            <div class="alert alert-danger mb-2">
                <ul>
                    @foreach (var message in ViewBag.ErrorMessages)
                    {
                        <li>@message</li>
                    }
                </ul>
            </div>
        }
        <div asp-validation-summary="ModelOnly" class="alert alert-danger mb-2"></div>
        <form asp-controller="Settings" asp-action="Password" method="post">
            <div class="form__group">
                <label class="form__label" asp-for="Password"></label>
                <input class="form__input" asp-for="Password" />
            </div>
            <div class="form__group">
                <label class="form__label" asp-for="PasswordCopy"></label>
                <input class="form__input" asp-for="PasswordCopy" />
            </div>
            <button class="btn btn-primary btn-block mt-2">Şifre Değiştir</button>
        </form>
    </div>
</div>